---
title: "Warm Up"
output: html_document
date: "2024-01-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 1. Plant Height Vector
```{r}
plant_heights <- c(30.7, 37.6, 28.4, NA, 33.2)
```

### 2. Plant Weight Vector
```{r}
plant_weights <- c(4, 5.2, 3.7, NA, 4.6)
```

### 3. Labels for data matrix
```{r}
samples <- c("plant1", "plant2", "plant3", "plant4", "plant5")
measured <- c("height", "weight")
```

### 4. Combine data for height and weight
```{r}
plant_experiment <- c(plant_heights, plant_weights)
```

### 5. Build the Data matrix
```{r}
plant_experiment_matrix <- matrix(plant_experiment, nrow = 5, byrow =F) # if sort by row, data goes left to right
plant_experiment_matrix
```
### 6. Name the columns and rows
```{r}
colnames(plant_experiment_matrix) <- measured
rownames(plant_experiment_matrix) <- samples
plant_experiment_matrix
```
### 7. Calculate the means of each column
```{r}
means <- colMeans(plant_experiment_matrix, na.rm=T)
means
```

### 8. Add this as a new row
```{r}
plant_experiment_matrix_final <- rbind(plant_experiment_matrix, means)
plant_experiment_matrix_final
```


